//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using Microsoft.EntityFrameworkCore;
    using RestaurentAngular.Models;
    using System;

    
    public partial class DBModel : DbContext
    {
     //   public DBModel()
        //    : base("name=DBModel") => base.Configuration.ProxyCreationEnabled = false;



        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderItem> OrderItems { get; set; }
    }
}
